spring:
#  profiles:
#    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 9999
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 18
mybatis:
  mapper-locations: classpath:mappers/*.xml

Knife4j:
  enable: true
logging:
  level:
    cn.tedu.csmall.product: trace